all: prob1 prob2 prob3

prob1: cscd340lab3prob1.c
	gcc -o prob1 cscd340lab3prob1.c

prob2: cscd340lab3prob2.c
	gcc -o prob2 cscd340lab3prob2.c

prob3: cscd340lab3prob3.c
	gcc -o prob3 cscd340lab3prob3.c
