all: prob1 prob2 prob3 prob4 prob5 prob6

prob1: lab5prob1.c
	gcc -o prob1 lab5prob1.c -lpthread

prob2: lab5prob2.c
	gcc -o prob2 lab5prob2.c -lpthread

prob3: lab5pc1.c
	gcc -o prob3 lab5pc1.c -lpthread

prob4: lab5pc2.c
	gcc -o prob4 lab5pc2.c -lpthread

prob5: lab5pc3.c
	gcc -o prob5 lab5pc3.c -lpthread

prob6: lab5pc4.c
	gcc -o prob6 lab5pc4.c -lpthread

